# Generated by Django 5.2.3 on 2026-01-28 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrosswordPuzzle',
            fields=[
                ('puzzle_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=50, null=True)),
                ('grid_size', models.IntegerField(default=81)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'crossword_puzzles',
            },
        ),
        migrations.CreateModel(
            name='CrosswordSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.IntegerField()),
                ('time_taken', models.IntegerField()),
                ('filled_cells', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.crosswordpuzzle')),
            ],
            options={
                'db_table': 'crossword_submissions',
            },
        ),
        migrations.CreateModel(
            name='CrosswordClue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.IntegerField()),
                ('direction', models.CharField(choices=[('across', 'Across'), ('down', 'Down')], max_length=6)),
                ('hint', models.TextField()),
                ('answer', models.CharField(blank=True, max_length=50, null=True)),
                ('answer_length', models.IntegerField()),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clues', to='hackathon.crosswordpuzzle')),
            ],
            options={
                'db_table': 'crossword_clues',
                'unique_together': {('puzzle', 'cell_id', 'direction')},
            },
        ),
        migrations.CreateModel(
            name='CrosswordBlackCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_number', models.IntegerField()),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_cells', to='hackathon.crosswordpuzzle')),
            ],
            options={
                'db_table': 'crossword_black_cells',
                'unique_together': {('puzzle', 'cell_number')},
            },
        ),
    ]
