# Generated by Django 5.2.3 on 2026-01-29 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crosswordpuzzlebank',
            fields=[
                ('puzzleid', models.CharField(db_column='puzzleID', max_length=20, primary_key=True, serialize=False)),
                ('blackboxarray', models.CharField(blank=True, db_column='blackBoxArray', max_length=200, null=True)),
                ('accrosshintarray', models.TextField(blank=True, db_column='accrossHintArray', null=True)),
                ('downhintarray', models.TextField(blank=True, db_column='downHintArray', null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='createdDate', null=True)),
            ],
            options={
                'db_table': 'crosswordpuzzlebank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('total_score', models.FloatField(default=0)),
                ('rounds_completed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'game_session',
                'ordering': ['-total_score', '-rounds_completed'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='crosswordclue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='crosswordclue',
            name='puzzle',
        ),
        migrations.RemoveField(
            model_name='crosswordsubmission',
            name='puzzle',
        ),
        migrations.CreateModel(
            name='PuzzleSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_id', models.CharField(max_length=20)),
                ('score', models.FloatField()),
                ('correct_words', models.IntegerField()),
                ('total_words', models.IntegerField()),
                ('time_remaining', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='hackathon.gamesession')),
            ],
            options={
                'db_table': 'puzzle_submission',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.DeleteModel(
            name='CrosswordBlackCell',
        ),
        migrations.DeleteModel(
            name='CrosswordClue',
        ),
        migrations.DeleteModel(
            name='CrosswordPuzzle',
        ),
        migrations.DeleteModel(
            name='CrosswordSubmission',
        ),
    ]
